import { LegalLayout } from "@/components/legal/legal-layout"

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Platform Disclaimer">

      <h2>Operational Assistance Disclaimer</h2>

      <p>
        TrueOps provides operational software tools intended to assist businesses with operational visibility,
        reporting and business management.
      </p>

      <h2>No Business Guarantees</h2>

      <p>
        The platform does not guarantee profitability, business growth,
        operational success or financial outcomes.
      </p>

      <h2>Data Accuracy</h2>

      <p>
        Reports and analytics generated by the platform depend on information entered by users.
      </p>

      <h2>Service Availability</h2>

      <p>
        While TrueOps aims to maintain reliable infrastructure,
        uninterrupted availability cannot be guaranteed.
      </p>

      <h2>Future Platform Evolution</h2>

      <p>
        The TrueOps ecosystem may evolve over time with new products,
        operational systems and features.
      </p>

    </LegalLayout>
  )
}